In [2]:
# imports
import pandas as pd
import polars as pl
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import polars.selectors as cs

# sklearn imports
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import VarianceThreshold

# for saving data
import pickle

In [3]:
# load data into lazyframes

#demo = pl.scan_csv("../data/raw/DemoStats_(DST)_2025_2025_GEO.csv", schema_overrides={"CODE": pl.String})
#hhs1 = pl.scan_csv("../data/raw/HouseholdSpend_(HHS)_2025_GEO_P1.csv", schema_overrides={"CODE": pl.String})
#hhs2 = pl.scan_csv("../data/raw/HouseholdSpend_(HHS)_2025_GEO_P2.csv", schema_overrides={"CODE": pl.String})


demo = pl.scan_csv("../data/DemoStats_2025_CSV_fixed/DemoStats_(DST)_2025_2025_GEO.csv", schema_overrides={"CODE": pl.String})
hhs1 = pl.scan_csv("../data/HouseholdSpend_2025_CSV_fixed/HouseholdSpend_(HHS)_2025_GEO_P1.csv", schema_overrides={"CODE": pl.String})
hhs2 = pl.scan_csv("../data/HouseholdSpend_2025_CSV_fixed/HouseholdSpend_(HHS)_2025_GEO_P2.csv", schema_overrides={"CODE": pl.String})

# merge hhs1 and hhs2
hhs = hhs1.join(hhs2, on=["CODE", "GEO"], how="inner")

In [3]:
# show descriptive stats (Skip bc it takes a few min to run)

# display(demo.describe())
# display(hhs.describe())

In [4]:
# show demo

demo.head().collect()

shape: (5, 736)
┌──────┬───────┬─────────────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ CODE ┆ GEO   ┆ ECYASQKM    ┆ ECYALSQKM   ┆ … ┆ ECYTCA_18P ┆ ECYNCANCIT ┆ ECYNCA_U18 ┆ ECYNCA_18P │
│ ---  ┆ ---   ┆ ---         ┆ ---         ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ str  ┆ str   ┆ f64         ┆ f64         ┆   ┆ i64        ┆ i64        ┆ i64        ┆ i64        │
╞══════╪═══════╪═════════════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 01   ┆ CAN   ┆ 9.8772e6    ┆ 9.5765e6    ┆ … ┆ 29078975   ┆ 4828559    ┆ 776329     ┆ 4052230    │
│ 000  ┆ CMACA ┆ 3.9106e6    ┆ 3.7982e6    ┆ … ┆ 49643      ┆ 1459       ┆ 143        ┆ 1316       │
│ 001  ┆ CMACA ┆ 990.22247   ┆ 951.50766   ┆ … ┆ 180221     ┆ 15980      ┆ 2451       ┆ 13529      │
│ 010  ┆ CMACA ┆ 57.771891   ┆ 55.043757   ┆ … ┆ 11571      ┆ 303        ┆ 62         ┆ 241        │
│ 011  ┆ CMACA ┆ 2658.109183 ┆ 2443.331205 ┆ … ┆ 11088      ┆ 460        ┆ 92         ┆ 368        │
└──────┴───────┴─────────────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [5]:
# filter demo to only include rows where GEO contains "PRCDDA"

demo = demo.filter(pl.col("GEO").str.contains("PRCDDA"))

demo.head().collect()

shape: (5, 736)
┌──────────┬────────┬──────────┬───────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ CODE     ┆ GEO    ┆ ECYASQKM ┆ ECYALSQKM ┆ … ┆ ECYTCA_18P ┆ ECYNCANCIT ┆ ECYNCA_U18 ┆ ECYNCA_18P │
│ ---      ┆ ---    ┆ ---      ┆ ---       ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ str      ┆ str    ┆ f64      ┆ f64       ┆   ┆ i64        ┆ i64        ┆ i64        ┆ i64        │
╞══════════╪════════╪══════════╪═══════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 10010165 ┆ PRCDDA ┆ 0.38455  ┆ 0.38455   ┆ … ┆ 452        ┆ 0          ┆ 0          ┆ 0          │
│ 10010166 ┆ PRCDDA ┆ 0.095564 ┆ 0.095564  ┆ … ┆ 301        ┆ 0          ┆ 0          ┆ 0          │
│ 10010167 ┆ PRCDDA ┆ 0.126296 ┆ 0.126296  ┆ … ┆ 373        ┆ 52         ┆ 5          ┆ 47         │
│ 10010168 ┆ PRCDDA ┆ 0.191336 ┆ 0.191336  ┆ … ┆ 468        ┆ 43         ┆ 4          ┆ 39         │
│ 10010169 ┆ PRCDDA ┆ 0.06591  ┆ 0.06591   ┆ … ┆ 278        ┆ 0          ┆ 0          ┆ 0          │
└──────────┴────────┴──────────┴───────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [6]:
# show hhs

hhs.head().collect()

shape: (5, 448)
┌──────┬───────┬──────────┬───────────┬───┬──────────────┬──────────────┬───────────┬──────────────┐
│ CODE ┆ GEO   ┆ HSBASHHD ┆ HSHNIAGG  ┆ … ┆ HSWH016      ┆ HSWH017      ┆ HSWH100   ┆ HSWH101      │
│ ---  ┆ ---   ┆ ---      ┆ ---       ┆   ┆ ---          ┆ ---          ┆ ---       ┆ ---          │
│ str  ┆ str   ┆ i64      ┆ f64       ┆   ┆ f64          ┆ f64          ┆ f64       ┆ f64          │
╞══════╪═══════╪══════════╪═══════════╪═══╪══════════════╪══════════════╪═══════════╪══════════════╡
│ 01   ┆ CAN   ┆ 16288077 ┆ 2.0943e12 ┆ … ┆ 8.2310e7     ┆ 4.1266e8     ┆ 1.5578e10 ┆ 4.0367e9     │
│ 000  ┆ CMACA ┆ 24133    ┆ 3.3437e9  ┆ … ┆ 112931.46225 ┆ 582101.27712 ┆ 2.0062e7  ┆ 5.5040e6     │
│      ┆       ┆          ┆           ┆   ┆ 2            ┆ 1            ┆           ┆              │
│ 001  ┆ CMACA ┆ 98080    ┆ 1.2340e10 ┆ … ┆ 49277.76939  ┆ 349050.46145 ┆ 7.8906e7  ┆ 2.2997e7     │
│ 010  ┆ CMACA ┆ 6403     ┆ 6.5841e8  ┆ … ┆ 2252.928934  ┆ 100903.92491 ┆ 3.0151e6  ┆ 656340.60282 │
│      ┆       ┆          ┆           ┆   ┆              ┆              ┆           ┆ 9            │
│ 011  ┆ CMACA ┆ 6155     ┆ 7.1158e8  ┆ … ┆ 3060.835741  ┆ 177233.65637 ┆ 3.6101e6  ┆ 920484.45855 │
│      ┆       ┆          ┆           ┆   ┆              ┆ 6            ┆           ┆ 3            │
└──────┴───────┴──────────┴───────────┴───┴──────────────┴──────────────┴───────────┴──────────────┘

In [7]:
# filter hhs to only include rows where GEO contains "PRCDDA"

hhs = hhs.filter(pl.col("GEO").str.contains("PRCDDA"))

hhs.head().collect()

shape: (5, 448)
┌──────────┬────────┬──────────┬──────────┬───┬───────────┬────────────┬─────────────┬─────────────┐
│ CODE     ┆ GEO    ┆ HSBASHHD ┆ HSHNIAGG ┆ … ┆ HSWH016   ┆ HSWH017    ┆ HSWH100     ┆ HSWH101     │
│ ---      ┆ ---    ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---        ┆ ---         ┆ ---         │
│ str      ┆ str    ┆ i64      ┆ f64      ┆   ┆ f64       ┆ f64        ┆ f64         ┆ f64         │
╞══════════╪════════╪══════════╪══════════╪═══╪═══════════╪════════════╪═════════════╪═════════════╡
│ 10010165 ┆ PRCDDA ┆ 227      ┆ 2.6823e7 ┆ … ┆ 81.880915 ┆ 238.14635  ┆ 213747.5082 ┆ 50801.20193 │
│          ┆        ┆          ┆          ┆   ┆           ┆            ┆ 13          ┆ 8           │
│ 10010166 ┆ PRCDDA ┆ 148      ┆ 2.0631e7 ┆ … ┆ 38.105455 ┆ 150.123809 ┆ 132661.6488 ┆ 26581.57664 │
│          ┆        ┆          ┆          ┆   ┆           ┆            ┆ 53          ┆ 3           │
│ 10010167 ┆ PRCDDA ┆ 217      ┆ 2.4982e7 ┆ … ┆ 55.752517 ┆ 274.405589 ┆ 192554.9718 ┆ 27863.83421 │
│          ┆        ┆          ┆          ┆   ┆           ┆            ┆ 51          ┆ 8           │
│ 10010168 ┆ PRCDDA ┆ 256      ┆ 2.9207e7 ┆ … ┆ 64.164596 ┆ 272.749813 ┆ 225708.3181 ┆ 37569.18016 │
│          ┆        ┆          ┆          ┆   ┆           ┆            ┆ 3           ┆ 6           │
│ 10010169 ┆ PRCDDA ┆ 132      ┆ 1.4251e7 ┆ … ┆ 37.345065 ┆ 163.203105 ┆ 98971.15476 ┆ 9061.92496  │
└──────────┴────────┴──────────┴──────────┴───┴───────────┴────────────┴─────────────┴─────────────┘

In [ ]:
# define HBR (HSSH001S/HSAGDISPIN)

hhs = hhs.with_columns((pl.col("HSSH001S") / pl.col("HSAGDISPIN")).alias("HBR"))

# if HSAGDISPIN is 0, set HBR to None (bc it would be inf)
hhs = hhs.with_columns(
    pl.when(pl.col("HSAGDISPIN") == 0).then(None).otherwise(pl.col("HBR")).alias("HBR")
)

# drop rows with none values (HBR)
hhs = hhs.filter(pl.col("HBR").is_not_null())

hhs.head().collect()

shape: (5, 449)
┌──────────┬────────┬──────────┬──────────┬───┬────────────┬──────────────┬─────────────┬──────────┐
│ CODE     ┆ GEO    ┆ HSBASHHD ┆ HSHNIAGG ┆ … ┆ HSWH017    ┆ HSWH100      ┆ HSWH101     ┆ HBR      │
│ ---      ┆ ---    ┆ ---      ┆ ---      ┆   ┆ ---        ┆ ---          ┆ ---         ┆ ---      │
│ str      ┆ str    ┆ i64      ┆ f64      ┆   ┆ f64        ┆ f64          ┆ f64         ┆ f64      │
╞══════════╪════════╪══════════╪══════════╪═══╪════════════╪══════════════╪═════════════╪══════════╡
│ 10010165 ┆ PRCDDA ┆ 227      ┆ 2.6823e7 ┆ … ┆ 238.14635  ┆ 213747.50821 ┆ 50801.20193 ┆ 0.204083 │
│          ┆        ┆          ┆          ┆   ┆            ┆ 3            ┆ 8           ┆          │
│ 10010166 ┆ PRCDDA ┆ 148      ┆ 2.0631e7 ┆ … ┆ 150.123809 ┆ 132661.64885 ┆ 26581.57664 ┆ 0.193655 │
│          ┆        ┆          ┆          ┆   ┆            ┆ 3            ┆ 3           ┆          │
│ 10010167 ┆ PRCDDA ┆ 217      ┆ 2.4982e7 ┆ … ┆ 274.405589 ┆ 192554.97185 ┆ 27863.83421 ┆ 0.198507 │
│          ┆        ┆          ┆          ┆   ┆            ┆ 1            ┆ 8           ┆          │
│ 10010168 ┆ PRCDDA ┆ 256      ┆ 2.9207e7 ┆ … ┆ 272.749813 ┆ 225708.31813 ┆ 37569.18016 ┆ 0.199864 │
│          ┆        ┆          ┆          ┆   ┆            ┆              ┆ 6           ┆          │
│ 10010169 ┆ PRCDDA ┆ 132      ┆ 1.4251e7 ┆ … ┆ 163.203105 ┆ 98971.15476  ┆ 9061.92496  ┆ 0.20826  │
└──────────┴────────┴──────────┴──────────┴───┴────────────┴──────────────┴─────────────┴──────────┘

In [9]:
# remove columns with HSSH

hhs = hhs.drop(cs.contains("HSSH"))

hhs.head().collect()

shape: (5, 400)
┌──────────┬────────┬──────────┬──────────┬───┬────────────┬──────────────┬─────────────┬──────────┐
│ CODE     ┆ GEO    ┆ HSBASHHD ┆ HSHNIAGG ┆ … ┆ HSWH017    ┆ HSWH100      ┆ HSWH101     ┆ HBR      │
│ ---      ┆ ---    ┆ ---      ┆ ---      ┆   ┆ ---        ┆ ---          ┆ ---         ┆ ---      │
│ str      ┆ str    ┆ i64      ┆ f64      ┆   ┆ f64        ┆ f64          ┆ f64         ┆ f64      │
╞══════════╪════════╪══════════╪══════════╪═══╪════════════╪══════════════╪═════════════╪══════════╡
│ 10010165 ┆ PRCDDA ┆ 227      ┆ 2.6823e7 ┆ … ┆ 238.14635  ┆ 213747.50821 ┆ 50801.20193 ┆ 0.204083 │
│          ┆        ┆          ┆          ┆   ┆            ┆ 3            ┆ 8           ┆          │
│ 10010166 ┆ PRCDDA ┆ 148      ┆ 2.0631e7 ┆ … ┆ 150.123809 ┆ 132661.64885 ┆ 26581.57664 ┆ 0.193655 │
│          ┆        ┆          ┆          ┆   ┆            ┆ 3            ┆ 3           ┆          │
│ 10010167 ┆ PRCDDA ┆ 217      ┆ 2.4982e7 ┆ … ┆ 274.405589 ┆ 192554.97185 ┆ 27863.83421 ┆ 0.198507 │
│          ┆        ┆          ┆          ┆   ┆            ┆ 1            ┆ 8           ┆          │
│ 10010168 ┆ PRCDDA ┆ 256      ┆ 2.9207e7 ┆ … ┆ 272.749813 ┆ 225708.31813 ┆ 37569.18016 ┆ 0.199864 │
│          ┆        ┆          ┆          ┆   ┆            ┆              ┆ 6           ┆          │
│ 10010169 ┆ PRCDDA ┆ 132      ┆ 1.4251e7 ┆ … ┆ 163.203105 ┆ 98971.15476  ┆ 9061.92496  ┆ 0.20826  │
└──────────┴────────┴──────────┴──────────┴───┴────────────┴──────────────┴─────────────┴──────────┘

In [10]:
# remove aggregates

hhs = hhs.drop(pl.col("HSAGDISPIN"))
hhs = hhs.drop(pl.col("HSAGDISCIN"))
hhs = hhs.drop(pl.col("HSHNIAGG"))
hhs = hhs.drop(pl.col("HSTT001"))
hhs = hhs.drop(pl.col("HSTE001"))
hhs = hhs.drop(pl.col("HSTX001"))
hhs = hhs.drop(pl.col("HSTC001"))

hhs.head().collect()

shape: (5, 393)
┌──────────┬────────┬──────────┬──────────┬───┬────────────┬──────────────┬─────────────┬──────────┐
│ CODE     ┆ GEO    ┆ HSBASHHD ┆ HSFD001S ┆ … ┆ HSWH017    ┆ HSWH100      ┆ HSWH101     ┆ HBR      │
│ ---      ┆ ---    ┆ ---      ┆ ---      ┆   ┆ ---        ┆ ---          ┆ ---         ┆ ---      │
│ str      ┆ str    ┆ i64      ┆ f64      ┆   ┆ f64        ┆ f64          ┆ f64         ┆ f64      │
╞══════════╪════════╪══════════╪══════════╪═══╪════════════╪══════════════╪═════════════╪══════════╡
│ 10010165 ┆ PRCDDA ┆ 227      ┆ 2.8802e6 ┆ … ┆ 238.14635  ┆ 213747.50821 ┆ 50801.20193 ┆ 0.204083 │
│          ┆        ┆          ┆          ┆   ┆            ┆ 3            ┆ 8           ┆          │
│ 10010166 ┆ PRCDDA ┆ 148      ┆ 1.9633e6 ┆ … ┆ 150.123809 ┆ 132661.64885 ┆ 26581.57664 ┆ 0.193655 │
│          ┆        ┆          ┆          ┆   ┆            ┆ 3            ┆ 3           ┆          │
│ 10010167 ┆ PRCDDA ┆ 217      ┆ 2.7642e6 ┆ … ┆ 274.405589 ┆ 192554.97185 ┆ 27863.83421 ┆ 0.198507 │
│          ┆        ┆          ┆          ┆   ┆            ┆ 1            ┆ 8           ┆          │
│ 10010168 ┆ PRCDDA ┆ 256      ┆ 3.1922e6 ┆ … ┆ 272.749813 ┆ 225708.31813 ┆ 37569.18016 ┆ 0.199864 │
│          ┆        ┆          ┆          ┆   ┆            ┆              ┆ 6           ┆          │
│ 10010169 ┆ PRCDDA ┆ 132      ┆ 1.6555e6 ┆ … ┆ 163.203105 ┆ 98971.15476  ┆ 9061.92496  ┆ 0.20826  │
└──────────┴────────┴──────────┴──────────┴───┴────────────┴──────────────┴─────────────┴──────────┘

In [11]:
# merge demo and hhs on CODE and GEO

data = hhs.join(demo, on="CODE", how="inner")

data.head().collect()

shape: (5, 1_128)
┌──────────┬────────┬──────────┬──────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ CODE     ┆ GEO    ┆ HSBASHHD ┆ HSFD001S ┆ … ┆ ECYTCA_18P ┆ ECYNCANCIT ┆ ECYNCA_U18 ┆ ECYNCA_18P │
│ ---      ┆ ---    ┆ ---      ┆ ---      ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ str      ┆ str    ┆ i64      ┆ f64      ┆   ┆ i64        ┆ i64        ┆ i64        ┆ i64        │
╞══════════╪════════╪══════════╪══════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 10010165 ┆ PRCDDA ┆ 227      ┆ 2.8802e6 ┆ … ┆ 452        ┆ 0          ┆ 0          ┆ 0          │
│ 10010166 ┆ PRCDDA ┆ 148      ┆ 1.9633e6 ┆ … ┆ 301        ┆ 0          ┆ 0          ┆ 0          │
│ 10010167 ┆ PRCDDA ┆ 217      ┆ 2.7642e6 ┆ … ┆ 373        ┆ 52         ┆ 5          ┆ 47         │
│ 10010168 ┆ PRCDDA ┆ 256      ┆ 3.1922e6 ┆ … ┆ 468        ┆ 43         ┆ 4          ┆ 39         │
│ 10010169 ┆ PRCDDA ┆ 132      ┆ 1.6555e6 ┆ … ┆ 278        ┆ 0          ┆ 0          ┆ 0          │
└──────────┴────────┴──────────┴──────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [12]:
# remove labels

data = data.drop(pl.col("CODE"))
data = data.drop(pl.col("GEO"))
data = data.drop(pl.col("GEO_right"))

data = data.collect()

data.head()

shape: (5, 1_125)
┌──────────┬──────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ HSBASHHD ┆ HSFD001S ┆ HSHO001S   ┆ HSHF001S  ┆ … ┆ ECYTCA_18 ┆ ECYNCANCI ┆ ECYNCA_U1 ┆ ECYNCA_18 │
│ ---      ┆ ---      ┆ ---        ┆ ---       ┆   ┆ P         ┆ T         ┆ 8         ┆ P         │
│ i64      ┆ f64      ┆ f64        ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆          ┆            ┆           ┆   ┆ i64       ┆ i64       ┆ i64       ┆ i64       │
╞══════════╪══════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 227      ┆ 2.8802e6 ┆ 1.3292e6   ┆ 711659.51 ┆ … ┆ 452       ┆ 0         ┆ 0         ┆ 0         │
│          ┆          ┆            ┆ 6933      ┆   ┆           ┆           ┆           ┆           │
│ 148      ┆ 1.9633e6 ┆ 917801.114 ┆ 462765.97 ┆ … ┆ 301       ┆ 0         ┆ 0         ┆ 0         │
│          ┆          ┆ 063        ┆ 7777      ┆   ┆           ┆           ┆           ┆           │
│ 217      ┆ 2.7642e6 ┆ 1.2585e6   ┆ 630450.46 ┆ … ┆ 373       ┆ 52        ┆ 5         ┆ 47        │
│          ┆          ┆            ┆ 807       ┆   ┆           ┆           ┆           ┆           │
│ 256      ┆ 3.1922e6 ┆ 1.4568e6   ┆ 743198.49 ┆ … ┆ 468       ┆ 43        ┆ 4         ┆ 39        │
│          ┆          ┆            ┆ 6523      ┆   ┆           ┆           ┆           ┆           │
│ 132      ┆ 1.6555e6 ┆ 735373.881 ┆ 379035.22 ┆ … ┆ 278       ┆ 0         ┆ 0         ┆ 0         │
│          ┆          ┆ 44         ┆ 333       ┆   ┆           ┆           ┆           ┆           │
└──────────┴──────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
# remove 0 variance col (done before splitting bc its the same between both sets anyways)

selector = VarianceThreshold(threshold=0)
selector.fit(data)
selected_cols = [col for col, keep in zip(data.columns, selector.get_support()) if keep]
data = data.select(selected_cols)

data.head()

shape: (5, 1_125)
┌──────────┬──────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ HSBASHHD ┆ HSFD001S ┆ HSHO001S   ┆ HSHF001S  ┆ … ┆ ECYTCA_18 ┆ ECYNCANCI ┆ ECYNCA_U1 ┆ ECYNCA_18 │
│ ---      ┆ ---      ┆ ---        ┆ ---       ┆   ┆ P         ┆ T         ┆ 8         ┆ P         │
│ i64      ┆ f64      ┆ f64        ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆          ┆            ┆           ┆   ┆ i64       ┆ i64       ┆ i64       ┆ i64       │
╞══════════╪══════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 227      ┆ 2.8802e6 ┆ 1.3292e6   ┆ 711659.51 ┆ … ┆ 452       ┆ 0         ┆ 0         ┆ 0         │
│          ┆          ┆            ┆ 6933      ┆   ┆           ┆           ┆           ┆           │
│ 148      ┆ 1.9633e6 ┆ 917801.114 ┆ 462765.97 ┆ … ┆ 301       ┆ 0         ┆ 0         ┆ 0         │
│          ┆          ┆ 063        ┆ 7777      ┆   ┆           ┆           ┆           ┆           │
│ 217      ┆ 2.7642e6 ┆ 1.2585e6   ┆ 630450.46 ┆ … ┆ 373       ┆ 52        ┆ 5         ┆ 47        │
│          ┆          ┆            ┆ 807       ┆   ┆           ┆           ┆           ┆           │
│ 256      ┆ 3.1922e6 ┆ 1.4568e6   ┆ 743198.49 ┆ … ┆ 468       ┆ 43        ┆ 4         ┆ 39        │
│          ┆          ┆            ┆ 6523      ┆   ┆           ┆           ┆           ┆           │
│ 132      ┆ 1.6555e6 ┆ 735373.881 ┆ 379035.22 ┆ … ┆ 278       ┆ 0         ┆ 0         ┆ 0         │
│          ┆          ┆ 44         ┆ 333       ┆   ┆           ┆           ┆           ┆           │
└──────────┴──────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [14]:
# split into train and test

X_train, X_test, y_train, y_test = train_test_split(data.drop('HBR'),
                                                    data.select('HBR'),
                                                    test_size = 0.2,
                                                    random_state = 42)

y_train = y_train.to_pandas().squeeze()
y_test = y_test.to_pandas().squeeze()

display(X_train.head())
display(y_train.head())

shape: (5, 1_124)
┌──────────┬──────────┬──────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ HSBASHHD ┆ HSFD001S ┆ HSHO001S ┆ HSHF001S   ┆ … ┆ ECYTCA_18P ┆ ECYNCANCI ┆ ECYNCA_U1 ┆ ECYNCA_18 │
│ ---      ┆ ---      ┆ ---      ┆ ---        ┆   ┆ ---        ┆ T         ┆ 8         ┆ P         │
│ i64      ┆ f64      ┆ f64      ┆ f64        ┆   ┆ i64        ┆ ---       ┆ ---       ┆ ---       │
│          ┆          ┆          ┆            ┆   ┆            ┆ i64       ┆ i64       ┆ i64       │
╞══════════╪══════════╪══════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 427      ┆ 4.6541e6 ┆ 2.1421e6 ┆ 1.0036e6   ┆ … ┆ 588        ┆ 148       ┆ 22        ┆ 126       │
│ 251      ┆ 2.7232e6 ┆ 1.3306e6 ┆ 768471.798 ┆ … ┆ 358        ┆ 136       ┆ 11        ┆ 125       │
│          ┆          ┆          ┆ 673        ┆   ┆            ┆           ┆           ┆           │
│ 339      ┆ 3.6457e6 ┆ 2.0880e6 ┆ 1.1454e6   ┆ … ┆ 649        ┆ 0         ┆ 0         ┆ 0         │
│ 283      ┆ 6.9016e6 ┆ 4.0215e6 ┆ 1.7887e6   ┆ … ┆ 621        ┆ 148       ┆ 22        ┆ 126       │
│ 616      ┆ 5.7970e6 ┆ 2.3875e6 ┆ 1.1706e6   ┆ … ┆ 848        ┆ 36        ┆ 2         ┆ 34        │
└──────────┴──────────┴──────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

0    0.274914
1    0.303569
2    0.241458
3    0.245380
4    0.247154
Name: HBR, dtype: float64

In [15]:
# handle missing values (calculate on train apply to test)

imputer = SimpleImputer(strategy='median')
X_train = pd.DataFrame(imputer.fit_transform(X_train), columns=X_train.columns)
X_test = pd.DataFrame(imputer.transform(X_test), columns=X_test.columns)

In [ ]:
# fit scaler on train apply to test

scaler = StandardScaler()
X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train), columns=X_train.columns)
X_test_scaled = pd.DataFrame(scaler.transform(X_test), columns=X_test.columns)

In [17]:
display(X_train.head())
display(y_train.head())

,HSBASHHD,HSFD001S,HSHO001S,HSHF001S,HSTR001S,HSHC001S,HSPC001S,HSRE001S,HSRO001S,HSTA018S,...,ECYGEN1GEN,ECYGEN2GEN,ECYGEN3GEN,ECYTCAHPOP,ECYTCACIT,ECYTCA_U18,ECYTCA_18P,ECYNCANCIT,ECYNCA_U18,ECYNCA_18P
0,427.0,4.654068e+06,2.142071e+06,1.003646e+06,4.341057e+06,1.334128e+06,9.262782e+05,2.147014e+06,95966.653907,1.802264e+06,...,250.0,166.0,435.0,851.0,703.0,115.0,588.0,148.0,22.0,126.0
1,251.0,2.723183e+06,1.330583e+06,7.684718e+05,2.513570e+06,6.026828e+05,4.216528e+05,1.165109e+06,77466.542677,1.148362e+06,...,304.0,84.0,173.0,561.0,425.0,67.0,358.0,136.0,11.0,125.0
2,339.0,3.645719e+06,2.087998e+06,1.145372e+06,3.520399e+06,9.994087e+05,5.257407e+05,1.693163e+06,126829.764682,1.257675e+06,...,73.0,146.0,565.0,784.0,784.0,135.0,649.0,0.0,0.0,0.0
3,283.0,6.901636e+06,4.021522e+06,1.788680e+06,8.686222e+06,2.307600e+06,1.386801e+06,3.571219e+06,76934.598655,2.681197e+06,...,420.0,223.0,254.0,897.0,749.0,128.0,621.0,148.0,22.0,126.0
4,616.0,5.796980e+06,2.387490e+06,1.170575e+06,3.530654e+06,1.332030e+06,8.757191e+05,2.031181e+06,120102.548051,1.817044e+06,...,136.0,158.0,773.0,1067.0,1031.0,183.0,848.0,36.0,2.0,34.0

0    0.274914
1    0.303569
2    0.241458
3    0.245380
4    0.247154
Name: HBR, dtype: float64

In [19]:
# save data

with open('../data/processed/tableau.pkl', 'wb') as f:
    pickle.dump({
        'X_train': X_train,
        'X_test': X_test,
        'X_train_scaled': X_train_scaled,
        'X_test_scaled': X_test_scaled,
        'y_train': y_train,
        'y_test': y_test,
        'scaler': scaler,
        'imputer': imputer
    }, f)

In [ ]:
print(f"Merged data shape: {data.shape}")
print(f"Features after leakage removal: {len(selected_cols) - 1}")